### ISSUE TITLE
Is there a way to sync all branches / tags?

### ISSUE THREAD

**Issue by connecteev** [TG908/fork-sync#17]
I am syncing a fork of a private repo I have access to.

This is my yml file:
```
name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: '*'
          head: '*'
```

But this is the error I see in my github actions log:
```
Check failure on line 1 in .github
@github-actions
github-actions
/ sync

.github#L1
Failed to create or merge pull request
```

what am I doing wrong? I need to sync ALL branches and tags from the original parent repo.

**Comment by connecteev** [comment]
Thanks @TG908 
This is what I am seeing with just the 'master' branch:

```
name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: master
```

In the github action log:
``` Run TG908/fork-sync@v1.1
##[error]Failed to create or merge pull request```

**Comment by TG908** [comment]
I think you are missing the `owner` of the repo you forked. See the example in README.md.

**Comment by TG908** [comment]
I don't know. I'll improve the error message in the next version, so we can dig deeper into this.

**Comment by TG908** [comment]
Try adding the `owner` field.

**Comment by connecteev** [comment]
Is 'owner' supposed to be the username of the source (someone else) or the destination repo (me)?
So it seems to have run successfully, but probably because the fork is already synced. I may have to recreate the fork and yml file again.
```No commits between connecteev:master and xxxxx:master```

**Comment by TG908** [comment]
owner is supposed to be the account name of the repository you forked from

**Comment by TG908** [comment]
No commits between connecteev:master and xxxxx:master sounds like your fork is synced and everything is working.

**Comment by connecteev** [comment]
Thank you for the clarification @TG908 :)
I'll monitor and report back if any issues are found!

**Comment by connecteev** [comment]
@TG908 so a quick update

Previously, it was working fine because it was a fresh fork, so there were no additional commits, and so I was seeing 
```
No commits between connecteev:master and xxxxx:master
```

However, after waiting a few days for the source repo to get updated, the sync has been failing. This is the email I have started to get every night: 

### Subject: Run failed for master (79c9c76)
Email body:
```
Run failed for master (79c9c76)
Repository: xxxxx/yyyyyyyy
Workflow: Sync Fork
Duration: 10 minutes and 40.0 seconds
Finished: 2020-08-29 00:13:44 UTC

View results

Jobs:
sync failed (1 annotation)
```

### The Error in github actions shows:
```
 Check failure on line 1 in .github

@github-actions
github-actions
/ sync

.github#L1
Failed to create or merge pull request
```

I did add the owner of the source repo to the yml file (copied below)
### .yml file:
```
name: Sync Fork

on:
  push:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: xxxxxxxx
          base: master
          head: master
```

Not sure what I am missing, but I'm curious if you have an idea.
