### ISSUE TITLE
Getting error "Validation failed"

### ISSUE THREAD

**Issue by jalaj-k** [TG908/fork-sync#18]
I have a project in my personal repo, which I have forked in my organisation repo. I just wanted to sync the `build` branch of base with the `gh-pages` branch of the head. This is the action file I am using:
```yaml
name: Deploy
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: jalaj-k
          head: gh-pages
          base: build
```

And, I am getting this error:

```
Failed to create or merge pull request: HttpError: Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}
```

What is this supposed to mean? What am I doing wrong? Or is this some bug? Or am i trying to do something that isn't possible?
