### ISSUE TITLE
Exclude action .yml from pull requests

### ISSUE THREAD

**Issue by tryallthethings** [TG908/fork-sync#21]
Hello!
Disclaimer: your action itself works great and this might be a layer 8 issue.
I'm contributing from time to time to a project on GitHub. So I forked it and set up your action to keep it updated. But when I create I pull request it will always include the configuration .yml which isn't needed in the original project. I've tried to add it to a branch but that prevents it from showing up in the GitHub actions.
Is there any other way besides removing the file each time before committing?

**Comment by TG908** [comment]
You could add the action in master and sync master2 and use this branch for your pull requests.

**Comment by tryallthethings** [comment]
Sounds like a good idea. While trying to get this to work (Git isn't my strong suit) I found a "task failed successfully" error:
https://github.com/tryallthethings/pikvm/runs/1117472427?check_suite_focus=true#step:2:10
![image](https://user-images.githubusercontent.com/11146296/93208196-82b25a80-f75c-11ea-8fbc-1c59c32402eb.png)
```
(node:2664) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at /home/runner/work/_actions/TG908/fork-sync/v1.2.0/lib/main.js:52:59
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/TG908/fork-sync/v1.2.0/lib/main.js:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Could you please let me know how to change my action to get your suggestion working?

**Comment by TG908** [comment]
Version 1.2.0 has some issues try using 1.2.1 or fall back to v1.1.

**Comment by tryallthethings** [comment]
Thanks, changed it. 
And in case anyone else wants to achieve the same, here's how I did it:

1. Forked the original repository 
2. Created a new branch "sync"
3. Created a new action on the master branch with the following .yml
```
name: Fork Sync

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.2
        with:
          owner: source-repo-owner
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: master
          base: sync
          merge_method: merge
          pr_title: Fork Sync
```

Now all changes from the original repo should be automatically merged to my sync repo and I can raise PR without the configuration .yml
